import type { Metadata } from "next";
import { Abril_Fatface, Anonymous_Pro, Besley, Fraunces } from "next/font/google";
import Link from "next/link";
import { FaTiktok } from "react-icons/fa6";
import { FiInstagram } from "react-icons/fi";
import "./globals.css";

const besley = Besley({
  variable: "--font-besley",
  subsets: ["latin"],
  weight: ["500", "700"],
});

const fraunces = Fraunces({
  variable: "--font-fraunces",
  subsets: ["latin"],
  weight: ["300", "700"],
});

const anonymousPro = Anonymous_Pro({
  variable: "--font-anonymous-pro",
  subsets: ["latin"],
  weight: ["400", "700"],
  style: ["normal", "italic"],
});

const abrilFatface = Abril_Fatface({
  variable: "--font-abril-fatface",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${besley.variable} ${fraunces.variable} ${anonymousPro.variable} ${abrilFatface.variable} antialiased`}
      >
        {children}
        <footer className="site-footer">
          <div className="site-footer-main">
            <div className="site-footer-upper">
              <div className="site-footer-copy">
                <h2>Join our cookie community</h2>
                <p>Subscribe now for exclusive offers and mouthwatering recipes!</p>
              </div>

              <form className="site-footer-form" aria-label="Newsletter signup">
                <label htmlFor="footer-email" className="sr-only">
                  Email address
                </label>
                <input
                  id="footer-email"
                  type="email"
                  placeholder="Email address"
                  className="site-footer-input"
                />
                <button type="submit" className="site-footer-button">
                  Sign up
                </button>
              </form>
            </div>

            <div className="site-footer-bottom-row">
              <p>
                {"\u00A9"} 2026 <span className="site-footer-brand">Grown Cookies</span>, Created by{" "}
                <a href="https://nathansomevi.dev" target="_blank" rel="noreferrer">
                  Somevi Labs
                </a>
              </p>
              <Link href="/terms">Terms and Policies</Link>
              <div className="site-footer-social">
                <Link href="#" aria-label="Instagram">
                  <FiInstagram />
                </Link>
                <Link href="#" aria-label="TikTok">
                  <FaTiktok />
                </Link>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}



